"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-26 17:53:37.942077
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_message_id', sa.Text(), nullable=False),
    sa.Column('contact_hash', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('script', sa.String(length=10), nullable=False),
    sa.Column('understood_by', sa.String(length=12), nullable=False),
    sa.Column('crop_ids', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('mandi_ids', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('reply_type', sa.String(length=24), nullable=True),
    sa.Column('price_record_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('holding_message_sent', sa.Boolean(), nullable=False),
    sa.CheckConstraint("channel IN ('whatsapp', 'sms')", name='channel'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'provider_message_id')
    )
    op.create_table('crops',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name_ur', sa.Text(), nullable=False),
    sa.Column('name_ur_latn', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('min_plausible_rs_40kg', sa.Integer(), nullable=False),
    sa.Column('max_plausible_rs_40kg', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('min_plausible_rs_40kg > 0 AND max_plausible_rs_40kg > min_plausible_rs_40kg', name='plausible_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandis',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name_ur', sa.Text(), nullable=False),
    sa.Column('name_ur_latn', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=False),
    sa.Column('province', sa.Text(), nullable=False),
    sa.Column('neighbours', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_clarifications',
    sa.Column('contact_hash', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('crop_id', sa.Text(), nullable=True),
    sa.Column('mandi_id', sa.Text(), nullable=True),
    sa.Column('awaiting', sa.String(length=10), nullable=False),
    sa.Column('script', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("awaiting IN ('crop', 'mandi')", name='awaiting'),
    sa.CheckConstraint("channel IN ('whatsapp', 'sms')", name='channel'),
    sa.PrimaryKeyConstraint('contact_hash', 'channel')
    )
    op.create_table('price_sources',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_name_ur', sa.Text(), nullable=False),
    sa.Column('display_name_ur_latn', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('terms_note', sa.Text(), nullable=True),
    sa.Column('terms_verified_on', sa.Date(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint("NOT enabled OR (terms_note IS NOT NULL AND terms_note <> '' AND terms_verified_on IS NOT NULL)", name='terms_before_enable'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synonyms',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('script', sa.String(length=10), nullable=False),
    sa.Column('text_normalized', sa.Text(), nullable=False),
    sa.CheckConstraint("entity_type IN ('crop', 'mandi')", name='entity_type'),
    sa.CheckConstraint("script IN ('ur', 'ur-Latn', 'en')", name='script'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'text_normalized')
    )
    op.create_table('price_records',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('crop_id', sa.Text(), nullable=False),
    sa.Column('mandi_id', sa.Text(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('min_rs_40kg', sa.Integer(), nullable=True),
    sa.Column('max_rs_40kg', sa.Integer(), nullable=True),
    sa.Column('original_unit', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status = 'rejected' OR ((min_rs_40kg IS NOT NULL OR max_rs_40kg IS NOT NULL) AND (min_rs_40kg IS NULL OR max_rs_40kg IS NULL OR min_rs_40kg <= max_rs_40kg))", name='valid_values'),
    sa.CheckConstraint("status = 'valid' OR reject_reason IS NOT NULL", name='reject_reason'),
    sa.CheckConstraint("status IN ('valid', 'rejected')", name='status'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['price_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'crop_id', 'mandi_id', 'price_date')
    )
    op.create_index('ix_price_records_lookup', 'price_records',
                    ['crop_id', 'mandi_id', 'price_date'])
    op.create_index('ix_conversation_turns_received_at', 'conversation_turns', ['received_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversation_turns_received_at', table_name='conversation_turns')
    op.drop_index('ix_price_records_lookup', table_name='price_records')
    op.drop_table('price_records')
    op.drop_table('synonyms')
    op.drop_table('price_sources')
    op.drop_table('pending_clarifications')
    op.drop_table('mandis')
    op.drop_table('crops')
    op.drop_table('conversation_turns')
    # ### end Alembic commands ###
